page-header murcked up&stylized
Valeriy-Fedulov/demo-project pull request #1
Opened 2021-05-28 15:16 UTC by Olena-Horobets

Guys, check out my awesome header! Also for some reason logo doesn't seem to be align vertically. Have I done something wrong? If so, let me know, please))

2021-05-28 16:56 UTC, vladibon requested changes
Your awesome header is perfect! It needs just a few fixes.

2021-05-28 16:56 UTC, vladibon commented on src/sass/_common.scss
> +  width: 1200px;
For better appearance, you should use max-width

2021-05-28 16:56 UTC, vladibon commented on src/sass/_page-header.scss
> +  height: 70px;
Don’t use height in this case.

2021-05-28 16:56 UTC, vladibon commented on src/sass/_page-header.scss
> +.main-nav__list {
Add also padding-left: 0; for main-nav__list

2021-05-28 17:31 UTC, Olena-Horobets commented on src/sass/_page-header.scss
> +.main-nav__list {
thank you, I forgot)

2021-05-28 17:38 UTC, vladibon approved these changes
That's really awesome now!

2021-05-29 10:55 UTC, Valeriy-Fedulov approved these changes

2021-05-29 10:57 UTC, merged